---
- name: Setup my dev environment on Ubuntu
  hosts: localhost
  gather_facts: true
  vars_files:
    - ./vars/user_vars.yml

  tasks:
  # Install tooling
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install general deps
      ansible.builtin.include_tasks: tasks/deps_install.yml

    - name: Install ansible-lint
      ansible.builtin.include_tasks: tasks/ansiblelint_install.yml

    - name: Setup git
      ansible.builtin.include_tasks: tasks/git_setup.yml

    - name: Install zsh
      ansible.builtin.include_tasks: tasks/zsh_install.yml

    - name: Install pip3
      ansible.builtin.include_tasks: tasks/pip3_install.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker_install.yml

    - name: Install kubectl
      ansible.builtin.include_tasks: tasks/kubectl_install.yml

    - name: Install minikube
      ansible.builtin.include_tasks: tasks/minikube_install.yml

    - name: Install helm
      ansible.builtin.include_tasks: tasks/helm_install.yml

    - name: Install terraform
      ansible.builtin.include_tasks: tasks/terraform_install.yml

    - name: Install azure cli
      ansible.builtin.include_tasks: tasks/azure_cli_install.yml

    - name: Install chrome
      ansible.builtin.include_tasks: tasks/chrome_install.yml

    - name: Install vscode
      ansible.builtin.include_tasks: tasks/vscode_install.yml
