---

- name: Setup my dev environment on Ubuntu
  hosts: localhost
  gather_facts: true
  vars_files:
    - ./vars/user_vars.yml


  tasks:
  # Install tooling
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      
    - name: Add Google Cloud public signing key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      register: google_cloud_key_added
      become: true
      changed_when: google_cloud_key_added is changed

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      register: kubernetes_repo_added
      become: true
      changed_when: kubernetes_repo_added is changed

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Apt-cache policy docker-ce
      ansible.builtin.command: apt-cache policy docker-ce
      register: docker_cache_policy
      become: true
      changed_when: docker_cache_policy is changed

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
      register: kubectl_installed
      become: true
      changed_when: kubectl_installed is changed

    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present
      become: true



    # Install runtimes and sdks

    - name: See if Nodesource list contains Node 16.x
      ansible.builtin.command: grep -c 'https://deb.nodesource.com/node_16.x' /etc/apt/sources.list.d/nodesource.list; true # grep returns 1 if no match
      register: nodesource_list_contains_node_16
      # if found return code will be non zero so ignore errors
      ignore_errors: true
      become: true

    - name: Add  Node.js 16.x apt repository if not found
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x focal main
        state: present
      when: 
        - nodesource_list_contains_node_16.stdout == "0"
      become: true


    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present
      register: nodejs_installed
      become: true
      changed_when: nodejs_installed is changed

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present
      register: npm_installed
      become: true
      changed_when: npm_installed is changed

    - name: Install pnpm
      ansible.builtin.npm:
        name: pnpm
        global: true
      register: pnpm_installed
      become: true
      changed_when: pnpm_installed is changed

    - name: Install dotnet 7 sdk
      ansible.builtin.apt:
        name: dotnet7
        state: present
      register: dotnet_sdk7_installed
      become: true
      changed_when: dotnet_sdk7_installed is changed

    - name: Install dotnet 8 sdk
      ansible.builtin.apt:
        name: dotnet8
        state: present
      register: dotnet_sdk8_installed
      become: true
      changed_when: dotnet_sdk8_installed is changed

    - name: Install Java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
      register: java11_installed
      become: true
      changed_when: java11_installed is changed

    - name: Install Java runtime
      ansible.builtin.apt:
        name: openjdk-11-jre
        state: present
      register: java_runtime_installed
      become: true
      changed_when: java_runtime_installed is changed

    # Install applications

    - name: Add Chrome key
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      become: true
      register: chrome_key_installed
      changed_when: chrome_key_installed is changed

    - name: Add Chrome repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
      register: chrome_repo_added
      become: true
      changed_when: chrome_repo_added is changed

    - name: Install Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
      register: chrome_installed
      become: true
      changed_when: chrome_installed is changed

    - name: Get install Jetbrains toolbox script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh
        dest: /tmp/jetbrains-toolbox.sh
        mode: 0755
      register: jetbrains_toolbox_script
      become: true
      changed_when: jetbrains_toolbox_script is changed


    - name: Install Jetbrains toolbox from the script
      ansible.builtin.command:
        cmd: /tmp/jetbrains-toolbox.sh
        creates: /opt/jetbrains-toolbox
      register: jetbrains_toolbox_installed
      become: true
      changed_when: jetbrains_toolbox_installed is changed

    - name: Install Postman, Discord, Spotify and Slack
      community.general.snap:
        name:
          - postman
          - discord
          - spotify
          - slack
        state: present
      register: snap_apps_installed
      become: true
      changed_when: snap_apps_installed is changed

    # Setup visuals, themes and icons

    - name: Install gnome-stuff
      ansible.builtin.apt:
        name:
          - gnome-tweaks
          - gnome-shell-extensions
          - chrome-gnome-shell
        state: present
      register: gnome_stuff_installed
      become: true
      changed_when: gnome_stuff_installed is changed

    - name: Download Azure Data Studio
      ansible.builtin.get_url:
        url: https://go.microsoft.com/fwlink/?linkid=2112886
        dest: /tmp/azuredatastudio.deb
        mode: 0755
      register: azure_data_studio_downloaded
      become: true
      changed_when: azure_data_studio_downloaded is changed

    - name: Install Azure Data Studio
      ansible.builtin.apt:
        deb: /tmp/azuredatastudio.deb
        state: present
      register: azure_data_studio_installed
      become: true
      changed_when: azure_data_studio_installed is changed

    - name: Start Jetbrains toolbox
      ansible.builtin.command:
        cmd: /opt/jetbrains-toolbox/jetbrains-toolbox
        creates: /home/mikael/.local/share/JetBrains/Toolbox
      register: jetbrains_toolbox_started
      become: true
      changed_when: jetbrains_toolbox_started is changed
