---
- name: Check if Azure CLI is already installed
  ansible.builtin.command: az --version
  register: azure_cli_installed
  ignore_errors: true
  changed_when: azure_cli_installed.rc != 0

- name: Install Azure CLI
  ansible.builtin.shell:
    cmd: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  when: azure_cli_installed.rc != 0
  args:
    executable: /bin/bash
  changed_when: azure_cli_installed.rc != 0
  become: true
