- name: Install general dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
    state: present
    update_cache: true
  become: true

- name: Ensure wget is installed
  ansible.builtin.apt:
    name: wget
    state: present
    update_cache: true
  become: true