---
- name: Uninstall conflicting packages for docker
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true
  register: docker_conflicting_uninstalled

- name: Check if /etc/apt/keyrings directory exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings
  register: keyrings_dir
  become: true

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: not keyrings_dir.stat.exists
  become: true

- name: Check if Docker GPG key is already in keyring
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg_key_file
  become: true

- name: Add Docker GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: not docker_gpg_key_file.stat.exists
  become: true
  changed_when: not docker_gpg_key_file.stat.exists
  register: docker_gpg_key_added

- name: Set permissions on Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r
  when: not docker_gpg_key_file.stat.exists and docker_gpg_key_added is changed
  become: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker
  become: true


- name: Install Docker components
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  register: docker_installed

- name: Ensure Docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ install_user }}"
    groups: docker
    append: true
  become: true

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  when: docker_installed is changed
