---
- name: Check if NVM is already installed
  ansible.builtin.command: nvm --version
  register: nvm_installed
  ignore_errors: true
  changed_when: false

- name: Install NVM (Node Version Manager)
  ansible.builtin.shell:
    cmd: curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    executable: /bin/bash
  register: nvm_installed
  become_user: "{{ install_user }}"
  changed_when: nvm_installed.stdout != ''
  when: nvm_installed.rc != 0
