- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  register: zsh_installed
  become: true
  changed_when: zsh_installed is changed

- name: Get oh my zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install.sh
    mode: 0755
  register: oh_my_zsh_downloaded
  become: true
  changed_when: oh_my_zsh_downloaded is changed

- name: Install oh my zsh
  ansible.builtin.command: /tmp/install.sh
  register: oh_my_zsh_installed
  become: true
  ignore_errors: true # This is a hack to ignore the error that oh-my-zsh throws when it's already installed
  changed_when: oh_my_zsh_installed is changed

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ install_user }}"
    shell: /usr/bin/zsh
  register: default_shell_changed
  become: true
  changed_when: default_shell_changed is changed