---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  register: zsh_installed
  become: true

- name: Get oh my zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: "0755"
  register: oh_my_zsh_downloaded
  become: true

- name: Install oh my zsh
  ansible.builtin.command: /tmp/ohmyzsh_install.sh
  register: oh_my_zsh_installed
  become: true
  ignore_errors: true # This is a hack to ignore the error that oh-my-zsh throws when it's already installed
  changed_when: oh_my_zsh_installed is changed

- name: Get oh my zsh config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/templates/zshrc.zsh-template
    dest: /home/{{ install_user }}/.zshrc
    mode: 0644
  register: oh_my_zsh_config_downloaded
  become: true
  changed_when: oh_my_zsh_config_downloaded is changed
